# Generated by Django 6.0.1 on 2026-02-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repetition',
            name='error',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='repetition',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ErrorScore',
        ),
    ]
