# Generated by Django 6.0.1 on 2026-03-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_analysis', '0003_recordingrecommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedvideo',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
