# Generated by Django 6.0.1 on 2026-04-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_analysis', '0004_recommendedvideo_language'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recording',
            table='recordings_fitness',
        ),
    ]
