# Generated by Django 6.0.1 on 2026-04-18 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(blank=True, max_length=50, null=True)),
                ('folder', models.CharField(blank=True, max_length=255, null=True)),
                ('total_frames', models.IntegerField(blank=True, null=True)),
                ('fatigue_level', models.CharField(blank=True, max_length=50, null=True)),
                ('analysis_result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatigue_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recordings_fatigue',
            },
        ),
    ]
