# Generated by Django 6.0.1 on 2026-04-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatigue_analysis', '0002_remove_recording_analysis_result_recording_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='fatigue_level',
        ),
        migrations.AddField(
            model_name='recording',
            name='vjump_height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
