# Generated by Django 6.0.1 on 2026-03-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='session_token',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
