# Generated by Django 6.0.1 on 2026-04-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0002_videosession_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='tag',
            field=models.CharField(default='unknown_tag', max_length=100),
        ),
    ]
